#!/bin/sh

if [ -f "ssos.hdd" ]; then
    rm -f ssos.hdd
fi

dd if=/dev/zero bs=1G count=0 seek=1 of=ssos.hdd

sgdisk ssos.hdd -n 1:2048:+200M -t 1:ef00 -c 1:"EFI partition"
sgdisk ssos.hdd -n 2:0:+1M -t 2:ef02 -c 2:"BIOS boot partition"
sgdisk ssos.hdd -n 3:0:0 -t 3:FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF -c 3:"Data partition"

if [ ! -d "limine" ]; then
    git clone https://github.com/limine-bootloader/limine.git --branch=v8.x-binary --depth=1
fi
make -C limine

dd if=ssos.hdd of=FAT32_sys_partition.img bs=512 skip=2048 count=409600

mformat -i FAT32_sys_partition.img
mmd -i FAT32_sys_partition.img ::/EFI ::/EFI/BOOT ::/boot ::/boot/limine
mcopy -i FAT32_sys_partition.img bin/ssos ::/boot
mcopy -i FAT32_sys_partition.img limine.conf limine/limine-bios.sys ::/boot/limine
mcopy -i FAT32_sys_partition.img limine/BOOTX64.EFI ::/EFI/BOOT
mcopy -i FAT32_sys_partition.img limine/BOOTIA32.EFI ::/EFI/BOOT

dd if=FAT32_sys_partition.img of=ssos.hdd bs=512 seek=2048 conv=notrunc
rm -f FAT32_sys_partition.img

./limine/limine bios-install ssos.hdd 2
