#!/bin/sh

dd if=/dev/zero bs=1m count=0 seek=64 of=ssos.hdd
sgdisk ssos.hdd -n 1:2048 -t 1:ef00 -m 1
git clone https://github.com/limine-bootloader/limine.git --branch=v8.x-binary --depth=1
make -C limine
./limine/limine bios-install ssos.hdd
mformat -i ssos.hdd@@1M
mmd -i ssos.hdd@@1M ::/EFI ::/EFI/BOOT ::/boot ::/boot/limine
mcopy -i ssos.hdd@@1M bin/ssos ::/boot
mcopy -i ssos.hdd@@1M limine.conf limine/limine-bios.sys ::/boot/limine
mcopy -i ssos.hdd@@1M limine/BOOTX64.EFI ::/EFI/BOOT
mcopy -i ssos.hdd@@1M limine/BOOTIA32.EFI ::/EFI/BOOT
