#!/bin/sh
qemu-system-x86_64 \
  -drive if=pflash,format=raw,readonly,file=$OVMF_PATH/OVMF_CODE.fd \
  -drive if=pflash,format=raw,file=$OVMF_PATH/OVMF_VARS.fd \
  -drive if=ide,file=ssos.hdd,format=raw \
  -serial stdio
